[connections.supabase]
url = "https://xxgqnxmvmaujzjmxmdhw.supabase.co"
key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh4Z3FueG12bWF1anpqbXhtZGh3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI1MjIwNzUsImV4cCI6MjA1ODA5ODA3NX0.l7PfaeDubGwT7PuBkLs1LgNBQKh9NIsWqSvZeo4Nr6Y"
